name: feature_search
description: "feature search package."
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  search_data:
    path: ../../data
  search_domain:
    path: ../../domain
  search_presentation:
    path: ../../presentation

#  search_di:
#    path: ../../di

  core_flutter_bloc:
    path: ../../../../core/flutter_bloc
  core_util:
    path: ../../../../core/util

  tool_community_component:
    path: ../../../../tool/community/component
  tool_community_network:
    path: ../../../../tool/community/network
  tool_community_theme:
    path: ../../../../tool/community/theme

#  feature_community:
#    path: ../../../../feature/community/target/community