name: core_util
description: "core util package."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  custom_refresh_indicator: 4.0.1
  event_bus: ^2.0.1
  flutter_svg: 2.2.0
  flutter_modular: ^6.4.1
  intl: 0.20.2
  provider: ^6.1.5
  shimmer: 3.0.0
  firebase_core: ^3.15.1
  firebase_remote_config: ^5.4.7