name: my_presentation
description: "feature my presentation package."
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  my_domain:
    path: ../domain

  core_bloc:
    path: ../../../core/bloc
  core_util:
    path: ../../../core/util