name: search_domain
description: "feature search domain package."
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  core_util:
    path: ../../../core/util

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0