name: core_flutter_bloc
description: "core flutter bloc package."
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  core_bloc:
    path: ../bloc

  flutter_bloc: ^9.1.1