name: waviz_client
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  go_router: ^16.1.0
  gap: ^3.0.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  dio: ^5.9.0
  retrofit: ^4.7.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.0
  image_picker: ^1.1.2
  dotted_border: ^3.1.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  retrofit_generator: ^9.2.0
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  custom_lint: ^0.7.6
  mockito: ^5.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/categories/
    - assets/icons/type/
    - assets/image/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900