name: community_server_prod
description: "server app using the shelf package."
version: 0.0.1

environment:
  sdk: ^3.8.0

dependencies:
  args: 2.7.0
  faker: 2.2.0
  json_annotation: 4.9.0
  shelf: 1.4.2
  shelf_router: 1.1.4
  shelf_swagger_ui: 1.0.0+2

dev_dependencies:
  build_runner: 2.5.4
  http: 1.4.0
  json_serializable: 6.9.5