name: workspace_melos

packages:
  - app/**
  - core/**
  - feature/**
  - server/**
  - tool/**

scripts:
  # usage: melos run setup
  setup:
    run: |
      melos exec -- rm -rf pubspec.lock && 
      melos run clean &&
      melos run update_packages &&
      melos run pub_get &&
      melos run build_runner

  # usage: melos run clean
  clean:
    run: melos exec -- flutter clean

  # usage: melos run update_packages
  update_packages:
    run: melos exec -- flutter update-packages --force-upgrade

  # usage: melos run pub_get
  pub_get:
    run: melos exec -c 1 -- flutter pub get

  # usage: melos run build_runner
  build_runner:
    run: melos exec -- depends-on="build_runner" -- flutter packages pub run build_runner build --delete-conflicting-outputs

  # usage : melos run update
#  update:
#    run: |
#      melos exec -- rm -rf pubspec.lock &&
#      melos run clean &&
#      melos bootstrap &&
#      melos exec -- rm -rf pubspec_overrides.yaml &&
#      melos exec -- "rm -rf melos*.iml"

  # usage : melos run pub_upgrade_major_versions
#  pub_upgrade_major_versions:
#    run: melos exec -- fvm flutter pub upgrade --major-versions

#  echo "Removing pubspec.lock..."
#  rm -f pubspec.lock || true
