name: tool_community_component
description: "tool community package."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  core_util:
    path: ../../../core/util

  tool_community_theme:
    path: ../theme

dev_dependencies:
  build_runner: 2.5.4
  flutter_gen_runner: 5.10.0
  very_good_analysis: ^9.0.0

flutter_gen:
  output: lib/gen/
  line_length: 120

flutter:
  assets:
    - assets/images/svgs/
