name: waviz_server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

dependencies:
  args: ^2.7.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  shelf_swagger_ui: 1.0.0+2
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  sqlite3: ^2.9.0
  path: ^1.9.1
  intl: ^0.20.2
  logging: ^1.3.0

dev_dependencies:
  http: ^1.5.0
  lints: ^6.0.0
  test: ^1.26.3
  build_runner: ^2.6.0
  freezed: ^3.2.0
  json_serializable: ^6.10.0
